import { it, expect } from "vitest";
import { screen, fireEvent } from "@testing-library/react";
import { act } from "@testing-library/react";
import { renderPage, mockFetchByUrl } from "../test/renderPage";
import Ingestion from "./Ingestion";

it("shows no invented profiling numbers without data", async () => {
  await renderPage(Ingestion, "/ingestion");
  for (const fake of ["10,100", "10,000", "-10 → 150", "305", "3.02"]) {
    expect(screen.queryAllByText(new RegExp(fake))).toHaveLength(0);
  }
});

it("keeps the import button disabled until a file is chosen", async () => {
  await renderPage(Ingestion, "/ingestion");
  expect(screen.getByRole("button", { name: "นำเข้าและตรวจข้อมูล" }).disabled).toBe(true);
});

it("does not offer an AI summary that is not generated by AI", async () => {
  await renderPage(Ingestion, "/ingestion");
  expect(screen.queryByText("สรุปจาก AI")).toBeNull();
});

it("explains a missing dataset instead of showing a server file path", async () => {
  await renderPage(Ingestion, "/ingestion");
  mockFetchByUrl([
    ["/ingest-source", { status: 404, body: { detail: "Dirty dataset not found at /app/student_course_score_evaluation_dataset/dirty_dataset.csv" } }]
  ]);
  fireEvent.click(screen.getByRole("tab", { name: "API" }));
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: /ดึงข้อมูล API/ }));
  });
  await act(async () => { await new Promise((r) => setTimeout(r, 50)); });
  expect(screen.getByRole("alert")).toHaveTextContent("ยังไม่มีข้อมูลในระบบ");
  expect(screen.queryByText(/\/app\//)).toBeNull();
});

it("reports issues found in any dataset's own columns, not only student columns", async () => {
  await renderPage(Ingestion, "/ingestion", [
    ["/whitebox/profile", { body: {
      total_rows: 562,
      total_columns: 5,
      columns_profile: {
        "วันที่": {},
        "รายการสินค้า": { null_count: 3 },
        "จำนวน": { outlier_count: 2 },
        "ราคาต่อหน่วย": {},
        "ยอดขายรวม": {}
      },
      duplicate_analysis: { tested_composite_key: [], duplicate_rows_detected: 0 }
    } }]
  ]);
  expect(screen.getByText(/พบปัญหา 2 ด้าน/)).toHaveTextContent(/ค่าว่าง 3/);
  expect(screen.getByText(/พบปัญหา 2 ด้าน/)).toHaveTextContent(/ผิดปกติ 2/);
  expect(screen.queryByText(/study_hours/)).toBeNull();
  expect(screen.queryByText(/ไม่พบปัญหาผิดปกติ/)).toBeNull();
});

it("labels the interactive API connector as a demo and shows no invented row count", async () => {
  await renderPage(Ingestion, "/ingestion");
  mockFetchByUrl([
    ["/ingest-source", { status: 200, body: { simulated: true, rows_ingested: null, profile: null } }]
  ]);
  fireEvent.click(screen.getByRole("tab", { name: "API" }));
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: /ดึงข้อมูล API/ }));
  });
  await act(async () => { await new Promise((r) => setTimeout(r, 50)); });
  expect(screen.getByText(/โหมดสาธิต/)).toBeTruthy();
  expect(screen.queryByText(/\(0 แถว\)/)).toBeNull();
});

async function fillDbForm() {
  fireEvent.click(screen.getByRole("tab", { name: /ฐานข้อมูล/ }));
  fireEvent.change(screen.getByPlaceholderText("postgres"), { target: { value: "postgres" } });
  fireEvent.change(screen.getByPlaceholderText("5432"), { target: { value: "5432" } });
  fireEvent.change(screen.getByPlaceholderText("ชื่อฐานข้อมูล"), { target: { value: "sdoqap_oltp" } });
  const inputs = document.querySelectorAll('input[autocomplete="off"], input[type="password"]');
  fireEvent.change(inputs[0], { target: { value: "reader" } });
  fireEvent.change(inputs[1], { target: { value: "secret" } });
  fireEvent.change(screen.getByPlaceholderText(/ชื่อตารางต้นทาง/), { target: { value: "student_scores_src" } });
}

it("sends the database form to the real RDBMS ingest and shows the run, not a demo notice", async () => {
  await renderPage(Ingestion, "/ingestion");
  const fn = mockFetchByUrl([
    ["/pipeline/ingest/rdbms", { status: 202, body: { status: "queued", ingest_id: "R1", rows_ingested: 10100 } }],
    ["/pipeline/runs/R1", { body: { state: "RUNNING" } }]
  ]);
  await fillDbForm();
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: "ดึงข้อมูลจากฐานข้อมูล" }));
  });
  await act(async () => { await new Promise((r) => setTimeout(r, 100)); });
  const call = fn.mock.calls.find(([url]) => String(url).includes("/pipeline/ingest/rdbms"));
  expect(call).toBeTruthy();
  const sent = JSON.parse(call[1].body);
  expect(sent).toMatchObject({ table_name: "student_scores_src", host: "postgres", port: 5432, database: "sdoqap_oltp", username: "reader", password: "secret", query: "SELECT * FROM student_scores_src" });
  expect(screen.getByText(/10,100 แถว/)).toBeTruthy();
  expect(screen.queryByText(/โหมดสาธิต/)).toBeNull();
  expect(fn.mock.calls.some(([url]) => String(url).includes("ingest-source"))).toBe(false);
});

it("shows the server's reason when the database ingest is refused", async () => {
  await renderPage(Ingestion, "/ingestion");
  mockFetchByUrl([
    ["/pipeline/ingest/rdbms", { status: 400, body: { detail: "Host 'x' is not in the RDBMS_ALLOWED_HOSTS allowlist." } }]
  ]);
  await fillDbForm();
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: "ดึงข้อมูลจากฐานข้อมูล" }));
  });
  await act(async () => { await new Promise((r) => setTimeout(r, 100)); });
  expect(screen.getByRole("alert")).toHaveTextContent(/allowlist|อนุญาต/);
});

async function uploadFile(routes) {
  const utils = await renderPage(Ingestion, "/ingestion");
  const fn = mockFetchByUrl(routes);
  const input = utils.container.querySelector('input[type="file"]');
  const file = new File(["student_id,score\n1,80\n"], "scores.csv", { type: "text/csv" });
  await act(async () => { fireEvent.change(input, { target: { files: [file] } }); });
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: "นำเข้าและตรวจข้อมูล" }));
  });
  await act(async () => { await new Promise((r) => setTimeout(r, 100)); });
  return fn;
}

const UPLOAD_OK = ["/whitebox/upload-csv", { body: { rows_ingested: 1, profile: { total_rows: 1, total_columns: 2, columns_profile: {} } } }];

it("also queues the uploaded file in the Spark pipeline and shows its run status", async () => {
  const fn = await uploadFile([
    UPLOAD_OK,
    ["/pipeline/ingest/csv", { status: 202, body: { status: "queued", ingest_id: "I1", run_state: "QUEUED" } }],
    ["/pipeline/runs/I1", { body: { state: "QUEUED" } }]
  ]);
  const queued = fn.mock.calls.filter(([url, opts]) => String(url).includes("/pipeline/ingest/csv") && opts?.method === "POST");
  expect(queued).toHaveLength(1);
  expect(queued[0][1].body.get("table_name")).toBe("scores");
  expect(queued[0][1].body.get("file").name).toBe("scores.csv");
  expect(screen.getByText(/สถานะรอบ: รอคิวตรวจ/)).toBeTruthy();
});

it("says so when the same file was already ingested instead of showing a run", async () => {
  await uploadFile([
    UPLOAD_OK,
    ["/pipeline/ingest/csv", { status: 200, body: { status: "duplicate", ingest_id: "I1", run_state: "SUCCEEDED" } }]
  ]);
  expect(screen.getByText(/เคยนำเข้าไฟล์นี้แล้ว/)).toBeTruthy();
  expect(screen.queryByText(/สถานะรอบ/)).toBeNull();
});

it("reports a pipeline failure without hiding the profile that was already computed", async () => {
  await uploadFile([
    UPLOAD_OK,
    ["/pipeline/ingest/csv", { status: 400, body: { detail: "File is missing primary key column(s) ['student_id'] registered for 'scores'." } }]
  ]);
  expect(screen.getByRole("alert")).toHaveTextContent("ส่งเข้าคิวตรวจคุณภาพ");
  expect(screen.getByText(/นำเข้า 'scores.csv' แล้ว/)).toBeTruthy();
});
