import { it, expect } from "vitest";
import { screen, fireEvent } from "@testing-library/react";
import { act } from "@testing-library/react";
import { renderPage, mockFetchByUrl } from "../test/renderPage";
import Ingestion from "./Ingestion";

it("shows no invented profiling numbers without data", async () => {
  await renderPage(Ingestion, "/ingestion");
  for (const fake of ["10,100", "10,000", "-10 → 150", "305", "3.02"]) {
    expect(screen.queryAllByText(new RegExp(fake))).toHaveLength(0);
  }
});

it("keeps the import button disabled until a file is chosen", async () => {
  await renderPage(Ingestion, "/ingestion");
  expect(screen.getByRole("button", { name: "นำเข้าและตรวจข้อมูล" }).disabled).toBe(true);
});

it("does not offer an AI summary that is not generated by AI", async () => {
  await renderPage(Ingestion, "/ingestion");
  expect(screen.queryByText("สรุปจาก AI")).toBeNull();
});

it("explains a missing dataset instead of showing a server file path", async () => {
  await renderPage(Ingestion, "/ingestion");
  mockFetchByUrl([
    ["/ingest-source", { status: 404, body: { detail: "Dirty dataset not found at /app/student_course_score_evaluation_dataset/dirty_dataset.csv" } }]
  ]);
  fireEvent.click(screen.getByRole("tab", { name: /ฐานข้อมูล/ }));
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: /ดึงข้อมูล RDBMS/ }));
  });
  await act(async () => { await new Promise((r) => setTimeout(r, 50)); });
  expect(screen.getByRole("alert")).toHaveTextContent("ยังไม่มีข้อมูลในระบบ");
  expect(screen.queryByText(/\/app\//)).toBeNull();
});

it("says the automatic checks need specific columns instead of reporting no problems", async () => {
  await renderPage(Ingestion, "/ingestion", [
    ["/whitebox/profile", { body: {
      total_rows: 562,
      total_columns: 5,
      columns_profile: { "วันที่": {}, "รายการสินค้า": {}, "จำนวน": {}, "ราคาต่อหน่วย": {}, "ยอดขายรวม": {} },
      duplicate_analysis: { tested_composite_key: [], duplicate_rows_detected: 0 }
    } }]
  ]);
  expect(screen.getByRole("status")).toHaveTextContent("study_hours");
  expect(screen.queryByText(/ไม่พบปัญหา/)).toBeNull();
  expect(screen.queryByText("ค่าว่างและช่วงค่า")).toBeNull();
});
